name: Release & Publish

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Init git user
        run: |
          git config --global user.email "cleber.gomes@kub3.dev"
          git config --global user.name "Release Workflow"
      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
